# Generated by Django 5.0 on 2024-11-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='total',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=20),
            preserve_default=False,
        ),
    ]
