# Generated by Django 5.0 on 2024-11-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_income_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='total',
        ),
    ]
